# Generated by Django 5.1.3 on 2024-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_or_admin', '0004_alter_guestoradmin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestoradmin',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guestoradmin',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
