# Generated by Django 5.1.3 on 2024-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Checked-in', 'Checked-in'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
