# Generated by Django 5.1.3 on 2024-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0038_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('1', '⭐'), ('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
